yatube/posts/urls.py
from django.urls import include, path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='main_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),   
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Group(models.Model):
    '''
    Класс формирования групп постов из БД
    '''
    title = models.TextField()
    slug = models.SlugField()
    description = models.TextField()

    def __str__(self):
        return self.title

  
class Post(models.Model):
    '''
    Класс формирования постов из БД
    '''
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
                              User,
                              on_delete=models.CASCADE,
                              related_name='posts')
    group = models.ForeignKey(
                              Group,
                              blank=True,
                              null = True,
                              on_delete = models.CASCADE)

yatube/posts/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Post, Group

def index(request):
    '''
    view функция вывода главной страницы
    '''
    posts = Post.objects.order_by('-pub_date')[:10]
    title = 'Последние обновления на сайте' # заголовок страницы
    context = {
               'posts': posts,
               'title' : title,
              }
    return render(request, 'posts/index.html', context)

def group_posts(request, slug):
    '''
    view функция вывода страниц-групп постов
    '''
    group = get_object_or_404(Group, slug=slug)
    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
               'group': group,
               'posts': posts,
               }
    return render(request, 'posts/group_list.html', context)

yatube/templates/base.html
<!DOCTYPE html>

<html lang="ru">
  <head> 
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="img/fav/fav.ico" type="image">
    <link rel="apple-touch-icon" sizes="180x180" href="img/fav/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/fav/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/fav/favicon-16x16.png">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="css/bootstrap.min.css">
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <header>
        {% include 'includes/header.html' %}
    </header>
    <main> 
        {% block content %}
        {% endblock %}    
    </main>        
    <footer class="border-top text-center py-3">
        {% include 'includes/footer.html' %} 
    </footer>
  </body>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
  <p>© 2021 Copyright <span style="color:red">Ya</span>tube</p>    
</footer>

yatube/templates/includes/header.html
{% load static %}

<nav class="navbar navbar-light" style="background-color: lightskyblue">
  <div class="container">
    <a class="navbar-brand" href= "{% url 'posts:main_page' %}">
      <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span style="color:red">
        Ya
        </span>
        tube
    </a>
  </div> 
</nav>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}

<title>
  {% block title %}
    Записки сообщества {{ group.title }}
  {% endblock %}
</title>

{% block content %}
  <div class="container py-5">     
    <article>
      <h1>
        {{ group.title }}
      </h1>
      <p>
        {{ group.description }}
      </p>
      {% for post in posts %}
        <ul>
          <li>
          Автор: {{ post.author.get_full_name }}
          </li>
          <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
          </ul> 
        <p>
          {{ post.text }}
        </p>
        {% if not forloop.last %}
          <hr>
        {% elif forloop.last %}
          <br>
        {% endif %}
      {% endfor %}
    </article>
  </div>
{% endblock content %}

yatube/templates/posts/index.html
{% extends 'base.html' %}

<title>
  {% block title %}
    {{ title }}
  {% endblock %}
</title>

{% block content %}
  <div class="container py-5">     
    <h1>
      Последние обновления на сайте
    </h1>
    <article>
      {% for post in posts %}
        <ul>
          <li>
          Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul> 
        <p>
          {{ post.text }}
        </p>
        <a 
          href="{% url 'posts:group_list' post.group.slug %}">
          все записи группы
        </a>
      {% if not forloop.last %}<hr>{% endif %}
      {% endfor %}
    </article>
  </div>
{% endblock %}    